app:
  name: tiklab-matflow

APP_HOME: ${APP_HOME}
application: matflow

server:
  port: 8080
  
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.13.1.13:5432/tiklab_matflow?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
DATA_HOME: /opt/tiklab/matflow

plugin:
  path: ${DATA_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${DATA_HOME}/caches

eas:
  embbed:
    enable: false
  address: http://bac.eas.tiklab.net

#message:
#  sms:
#    enabled: true

base:
  url: http://bac.matflow.tiklab.net

#homes
homes:
  address: http://192.168.10.19:8080

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.tiklab.net












