app:
  name: tiklab-matflow

APP_HOME: ${APP_HOME}

application: matflow

setting:
  address: tiklab-matflow-starter/src/main/resources/settings.xml

server:
  port: 8090

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_matflow?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
DATA_HOME: D:\opt\tiklab\matflow

plugin:
  path: ${DATA_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
#    enabled: true
    enabled: false
    port: 5020
    datapath: ${DATA_HOME}/caches
  client:
#    url: 127.0.0.1:5020
    url: 127.0.0.1:5035
    group: g1
    database: dcs1
    expire: 7200

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${DATA_HOME}/caches

#message:
#  sms:
#    enabled: true

eas:
  embbed:
#    enable: true
    enable: false
  address: http://192.168.10.19:8080
  web:
    address: http://192.168.10.11:3010


postgresql:
  embbed:
    enable: false
  database: tiklab_matflow


base:
  url: http://192.168.10.5:3000

#homes
homes:
  address: http://192.168.10.7:8080

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.dev.tiklab.net













