app:
  name: thoughtware-arbess

APP_HOME: ${APP_HOME}

application: arbess

spring:
  main:
    allow-bean-definition-overriding: true
  freemarker:
    checkTemplateLocation: false

arbess:
  setting:
    address: /Users/zcamy/Java/thoughtware-arbess-agent/thoughtware-arbess-agent-starter/src/main/resources/settings.xml
  spotbugs:
    address: /Users/zcamy/Java/thoughtware-arbess-agent/thoughtware-arbess-agent-starter/embbed/spotbugs-4.8.1/bin/spotbugs
  jdk:
    address: /Users/zcamy/Java/thoughtware-arbess-agent/thoughtware-arbess-agent-starter/embbed/jdk-16.0.2


server:
  port: 8090

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_matflow?stringtype=unspecified
#  url: jdbc:postgresql://172.13.1.22:5432/matflow_ee?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
DATA_HOME: ${user.home}/thoughtware/run_cache/matflow/

plugin:
  path: ${DATA_HOME}/plugin

ws:
  name: local
  server:
    enabled: true
  enterprise: default
  url : 127.0.0.1:8090

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: true
    port: 5020
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5020
    group: g1
    database: dcs1
    expire: 7200

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${DATA_HOME}/caches

#message:
#  sms:
#    enabled: true

soular:
  embbed:
    enable: true
#    enable: false
#  address: http://192.168.10.10:8080
#  web:
#    address: http://192.168.10.13:3010


backups:
#  pgsql:
#    dir:
  dir: ${user.home}/thoughtware/run_cache/data/matflow
  time: 0 0 2 * * ?
  type: local

postgresql:
  embbed:
    enable: false
  database: tiklab_matflow
  type: local


base:
  url: http://192.168.10.13:3000

#homes
homes:
  address: https://homes.tiklab.net

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.dev.tiklab.net













