app:
  name: tiklab-matflow

APP_HOME: ${APP_HOME}
application: matflow

server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5000/matflow?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
DATA_HOME: /opt/tiklab/matflow

plugin:
  path: ${DATA_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${DATA_HOME}/caches

postgresql:
  embbed:
    enable: true
  database: matflow
  db:
    port: 5000
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

eas:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net

base:
  url: http://matflow-ce.demo.tiklab.net

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.demo.tiklab.net


#homes
homes:
  address: http://homes.demo.tiklab.net










