
server:
  port: 8080

app:
  name: arbess

APP_HOME: ${APP_HOME}

postgresql:
  embbed:
    enable: true
  database: arbess
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/arbess?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
DATA_HOME: /opt/tiklab/arbess

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

soular:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net


backups:
  dir: /data/matflow-ee
  time: 0 0 2 * * ?

base:
  url: http://matflow-ce.demo.tiklab.net

#license
licences:
  path: ${APP_HOME}/licences











