app:
  name: arbess

server:
  port: 8080

external:
  url: http://arbess-ce.demo.tiklab.net

postgresql:
  embbed:
    enable: true
  database: arbess
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/arbess?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
DATA_HOME: /opt/tiklab/arbess

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

auth:
  type: soualr
  soular:
    address: http://soular-ce.demo.tiklab.net












