app:
  name: tiklab-matflow

APP_HOME: ${APP_HOME}
application: matflow

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tiklab_matflow?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
DATA_HOME: ${user.home}/matflow/${app.name}

plugin:
  path: ${DATA_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
#dcs
dcs:
  server:
    enabled: true
    port: 5001
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 7200

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

eas:
  embbed:
    enable: true
  address: http://eas.prd.tiklab.net

postgresql:
  embbed:
    enable: true
  database: tiklab_matflow
  db:
    address: ${DATA_HOME}
    port: 5432

#message:
#  sms:
#    enabled: true

base:
  url: http://matflow.tiklab.net

#homes
homes:
  address: http://tiklab.net

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.tiklab.net












