app:
  name: tiklab-matflow

APP_HOME: ${APP_HOME}
application: matflow

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tiklab_matflow?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
PROJECT_HOME: ${user.home}/pipeline/${app.name}
plugin:
  path: ${PROJECT_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${PROJECT_HOME}/caches

eas:
  embbed:
    enable: true
  address: http://eas.tiklab.net

postgresql:
  embbed:
    enable: true
  database: tiklab_matflow

#message:
#  sms:
#    enabled: true

base:
  url: http://matflow.tiklab.net

#homes
homes:
  address: http://tiklab.net

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.tiklab.net












