app:
  name: arbess

spring:
  main:
    allow-bean-definition-overriding: true
  freemarker:
    checkTemplateLocation: false

arbess:
  setting:
#    address: /Users/zcamy/Java/tiklab-arbess-agent/tiklab-arbess-agent-starter/src/main/resources/settings.xml
    address: D:\Java\tiklab-arbess-agent\tiklab-arbess-agent-starter\src\main\resources\settings.xml
  spotbugs:
    address: /Users/zcamy/Java/tiklab-arbess-agent/tiklab-arbess-agent-starter/embbed/spotbugs-4.8.1/bin/spotbugs
  jdk:
    address: /Users/zcamy/apply/jdk-17.0.9.jdk/Contents/Home
  task:
    timeout: 300

server:
  port: 8090

APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/tiklab-arbess


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_arbess?stringtype=unspecified
  username: postgres
  password: darth2020

#jdbc:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://172.10.1.10:3306/tiklab_arbess?characterEncoding=utf8&useSSL=false
#  username: root
#  password: darth2020

postgresql:
  embbed:
    enable: false
  database: tiklab-arbess
  type: local

postin:
  scan:
    package: io.tiklab.arbess



#dcs config
dcs:
  server:
    enabled: true
    port: 5020
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5020
    group: g1
    database: dcs1
    expire: 7200

auth:
  type: soularss
  soular:
    address: http://192.168.10.15:8080
    web:
      address: http://192.168.10.16:3010

backups:
  dir: ${DATA_HOME}/backups
  time: 0 0 2 * * ?
  type: local

ws:
  name: local
  server:
    enabled: true
  enterprise: default
  url : 127.0.0.1:8090


base:
  url: http://localhost:8090

#license
licences:
  path: ${DATA_HOME}/licences













