app:
  name: arbess

server:
  port: 8090

DATA_HOME: ${user.home}/tiklab/tiklab-arbess

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_arbess?stringtype=unspecified
  username: postgres
  password: darth2020

#jdbc:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://172.10.1.10:3306/tiklab_arbess?characterEncoding=utf8&useSSL=false
#  username: root
#  password: darth2020

postgresql:
  embbed:
    enable: false
  database: tiklab-arbess
  type: local

#dcs config
dcs:
  server:
    enabled: true
    port: 5020
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5020
    group: g1
    database: dcs1
    expire: 7200

auth:
  type: local
  soular:
    address: http://192.168.10.15:8080
    web:
      address: http://192.168.10.16:3010

arbess:
  task:
    timeout: 300

ws:
  name: local
  server:
    enabled: true
  enterprise: default
  url : 127.0.0.1:8090


external:
  url: http://localhost:8090












