app:
  name: arbess

spring:
  main:
    allow-bean-definition-overriding: true
  freemarker:
    checkTemplateLocation: false


server:
  port: 8090

APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/tiklab-arbess


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_matflow?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: false
  database: tiklab-arbess
  type: local

#dcs config
dcs:
  server:
    enabled: true
    port: 5020
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5020
    group: g1
    database: dcs1
    expire: 7200

soular:
  embbed:
    enable: true
#    enable: false
#  address: http://192.168.10.15:8080
#  web:
#    address: http://192.168.10.16:3010


backups:
  dir: ${DATA_HOME}/backups
  time: 0 0 2 * * ?
  type: local

ws:
  name: local
  server:
    enabled: true
  enterprise: default
  url : 127.0.0.1:8090


base:
  url: http://localhost:8090

#license
licences:
  path: ${DATA_HOME}/licences













