app:
  name: thoughtware-matflow-ce

APP_HOME: ${APP_HOME}
application: matflow-ce

server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/matflow_ce?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
DATA_HOME: /opt/thoughtware/matflow-ce

plugin:
  path: ${DATA_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

postgresql:
  embbed:
    enable: true
  database: matflow_ce
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

datapath: ${DATA_HOME}/caches

eas:
  embbed:
    enable: false
  address: http://eas-ce.demo.thoughtware.cn


backups:
  dir: /data/matflow-ee
  #    time: 0 */1 * * * ?
  time: 0 0 2 * * ?

#message:
#  sms:
#    enabled: true

base:
  url: http://matflow-ce.demo.thoughtware.cn

#homes
homes:
  address: http://thoughtware.cn

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.thoughtware.cn












