app:
  name: arbess

APP_HOME: ${APP_HOME}

server:
  port: 8080

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
  main:
    allow-bean-definition-overriding: true

postgresql:
  embbed:
    enable: true
  database: arbess
  db:
    port: 6000
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:6000/arbess?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
DATA_HOME: /opt/tiklab/arbess

#dcs config
dcs:
  server:
    enabled: true
    port: 5020
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5020
    group: g1
    database: dcs1
    expire: 7200

auth:
  type: local
  soular:
    address: http://e.soular.tiklab.net
external:
  url: http://localhost:8080









